# Numbers

In [11]:
%matplotlib inline

In [12]:
import numpy as np

## The `ndarray`: Vectors, matrices and tenosrs

dtype, shape, strides

### Vector

In [28]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [17]:
type(x)

numpy.ndarray

In [19]:
x.dtype

dtype('int64')

In [18]:
x.shape

(3,)

In [20]:
x.strides

(8,)

### Matrix

In [29]:
x = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [25]:
x.dtype

dtype('int32')

In [26]:
x.shape

(2, 3)

In [27]:
x.strides

(12, 4)

### Tensor

In [30]:
x = np.arange(24).reshape((2,3,4))

In [31]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Creating `ndarray`s

### From a file

In [85]:
%%file numbers.txt
a,b,c # can also skip headers
1,2,3
4,5,6

Overwriting numbers.txt


In [87]:
np.loadtxt('numbers.txt', dtype='int', delimiter=',',
           skiprows=1, comments='#')

array([[1, 2, 3],
       [4, 5, 6]])

### From Python lists or tuples

In [32]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

### From ranges

arange, linspace, logspace

In [34]:
np.arange(1, 7).reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [52]:
np.logspace(0, 4, 5, dtype='int')

array([    1,    10,   100,  1000, 10000])

### From a function

fromfunciton

In [36]:
np.fromfunction(lambda i, j: i*3 + j + 1, (2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
np.fromfunction(lambda i, j: (i-2)**2 + (j-2)**2, (5,5))

array([[8., 5., 4., 5., 8.],
       [5., 2., 1., 2., 5.],
       [4., 1., 0., 1., 4.],
       [5., 2., 1., 2., 5.],
       [8., 5., 4., 5., 8.]])

In [76]:
np.fromfunction(lambda i, j: np.where(i<j, 1, np.where(i==j,0, -1)), (5,5))

array([[ 0,  1,  1,  1,  1],
       [-1,  0,  1,  1,  1],
       [-1, -1,  0,  1,  1],
       [-1, -1, -1,  0,  1],
       [-1, -1, -1, -1,  0]])

### From special construcotrs

zeoros, ones, eye

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### From random variables

#### Convenience functions

rand, randn

In [55]:
np.random.rand(2,3)

array([[0.92251324, 0.82910265, 0.04543481],
       [0.90060873, 0.81513891, 0.07333229]])

In [57]:
np.random.randn(2,3)

array([[-0.69364334, -1.30467092, -0.26471489],
       [-0.72727702,  0.55829322,  0.55036051]])

#### Distributions

uniform, normal, randint, poisson, multinomial, multivariate_ normal

In [60]:
np.random.uniform(0, 1, (2,3))

array([[0.21719604, 0.48598864, 0.8648672 ],
       [0.91863771, 0.01887129, 0.70096766]])

In [59]:
np.random.normal(0, 1, (2,3))

array([[ 2.49470357, -0.48582065,  1.92410035],
       [-0.12227825, -0.77345101, -0.77511657]])

In [62]:
np.random.randint(0, 10, (4,5))

array([[7, 1, 5, 3, 2],
       [6, 8, 3, 9, 9],
       [0, 3, 6, 7, 6],
       [7, 0, 9, 5, 4]])

In [63]:
np.random.poisson(10, (4,5))

array([[ 8, 10, 10, 10, 13],
       [10,  9, 11, 10, 11],
       [ 9,  6,  8, 12, 13],
       [10,  5, 12,  9,  9]])

In [69]:
np.random.multinomial(n=5, pvals=np.ones(5)/5, size=8)

array([[2, 2, 0, 1, 0],
       [1, 0, 1, 2, 1],
       [3, 0, 0, 2, 0],
       [1, 1, 1, 0, 2],
       [0, 3, 1, 1, 0],
       [1, 2, 2, 0, 0],
       [2, 1, 1, 0, 1],
       [1, 2, 0, 1, 1]])

In [71]:
np.random.multivariate_normal(mean=[10,20,30], cov=np.eye(3), size=4)

array([[ 9.95332345, 20.12239284, 29.78622179],
       [10.42394728, 21.20318228, 29.63107268],
       [10.13607957, 20.35000153, 30.6033475 ],
       [ 8.89458895, 20.1510175 , 30.51418431]])

## Indexing 

In [128]:
x = np.arange(20).reshape((4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Extracing a scalar

In [129]:
x[1,1]

6

### Extracting a vector

In [130]:
x[1]

array([5, 6, 7, 8, 9])

### Using slices

In [131]:
x[1,:]

array([5, 6, 7, 8, 9])

In [132]:
x[:,1]

array([ 1,  6, 11, 16])

In [133]:
x[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

### Using slices with strides

In [134]:
x[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

### Extrcting blocks with arbitrary row and column lists (fancy indexing)

`np.ix_`

In [135]:
x[:, [0,3]]

array([[ 0,  3],
       [ 5,  8],
       [10, 13],
       [15, 18]])

Warning: Fancy indexing can only be used for 1 dimension.

In [136]:
x[[0,2],[0,3]]

array([ 0, 13])

Use the helper `np.ix_` to extract arbitrary blocks.

In [137]:
x[np.ix_([0,2], [0,3])]

array([[ 0,  3],
       [10, 13]])

### Boolean indexing

In [138]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
x [x > 3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Functions that return indexes

In [140]:
idx = np.nonzero(x)
idx

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [141]:
x[idx]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [142]:
idx = np.where(x > 3)
idx

(array([0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [143]:
x[idx]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Margins and the `axis` argument

In [145]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

The 0th axis has 4 items, the 1st axis has 5 items.

In [146]:
x.shape

(4, 5)

In [161]:
x.mean()

0.5978804243526721

### Marginalizing out the 0th axis = column summaries

In [147]:
x.mean(axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

### Marginalizing out the 1st axis = row summaries

In [148]:
x.mean(axis=1)

array([ 2.,  7., 12., 17.])

Note marginalizing out the last axis is a common default.

In [149]:
x.mean(axis=-1)

array([ 2.,  7., 12., 17.])

### Marginalization works for higher dimensions in the same way

In [152]:
x = np.random.random((2,3,4))
x

array([[[0.93167594, 0.9834335 , 0.85066639, 0.84960191],
        [0.84754057, 0.05277862, 0.16360063, 0.63211457],
        [0.002987  , 0.60260786, 0.03378456, 0.9574152 ]],

       [[0.57637126, 0.73467854, 0.99619499, 0.13595993],
        [0.19816996, 0.93784557, 0.47997721, 0.92720469],
        [0.84264989, 0.36200676, 0.87893255, 0.37093209]]])

In [153]:
x.shape

(2, 3, 4)

In [154]:
x.mean(axis=0).shape

(3, 4)

In [155]:
x.mean(axis=1).shape

(2, 4)

In [156]:
x.mean(axis=2).shape

(2, 3)

In [158]:
x.mean(axis=(0,1)).shape

(4,)

In [159]:
x.mean(axis=(0,2)).shape

(3,)

In [160]:
x.mean(axis=(1,2)).shape

(2,)

## Broadcasting

In [170]:
x1 = np.arange(12)

In [165]:
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [167]:
x1 * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [184]:
x2 = np.random.randint(0,10,(3,4))

In [185]:
x2

array([[7, 6, 3, 3],
       [5, 7, 5, 3],
       [2, 2, 2, 4]])

In [186]:
x2 * 10

array([[70, 60, 30, 30],
       [50, 70, 50, 30],
       [20, 20, 20, 40]])

In [187]:
x2.shape

(3, 4)

### Column-wise broadcasting

In [188]:
mu = np.mean(x2, axis=0)
mu.shape

(4,)

In [189]:
x2 - mu

array([[ 2.33333333,  1.        , -0.33333333, -0.33333333],
       [ 0.33333333,  2.        ,  1.66666667, -0.33333333],
       [-2.66666667, -3.        , -1.33333333,  0.66666667]])

In [190]:
(x2 - mu).mean(axis=0)

array([-2.96059473e-16,  0.00000000e+00, -1.48029737e-16, -1.48029737e-16])

### Row wise broadcasting

In [191]:
mu = np.mean(x2, axis=1)
mu.shape

(3,)

In [198]:
try:
    x2 - mu
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,4) (3,) 


### We can add a "dummy" axis using None or `np.newaxis`

In [194]:
mu[:, None].shape

(3, 1)

In [196]:
x2 - mu[:, None]

array([[ 2.25,  1.25, -1.75, -1.75],
       [ 0.  ,  2.  ,  0.  , -2.  ],
       [-0.5 , -0.5 , -0.5 ,  1.5 ]])

In [201]:
x2 - mu[:, np.newaxis]

array([[ 2.25,  1.25, -1.75, -1.75],
       [ 0.  ,  2.  ,  0.  , -2.  ],
       [-0.5 , -0.5 , -0.5 ,  1.5 ]])

In [197]:
np.mean(x2 - mu[:, None], axis=1)

array([0., 0., 0.])

#### Reshaping works too

In [200]:
x2 - mu.reshape((-1,1))

array([[ 2.25,  1.25, -1.75, -1.75],
       [ 0.  ,  2.  ,  0.  , -2.  ],
       [-0.5 , -0.5 , -0.5 ,  1.5 ]])

## Vectorization

### Example 1

The operators and functions (ufuncs) in Python are vectorized, and will work element-wise over all entries in an `ndarray`.

In [267]:
xs = np.zeros(10, dtype='int')
for i in range(10):
    xs[i] = i**2
xs

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [268]:
xs = np.arange(10)**2
xs

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Using ufuncs

In [269]:
np.sqrt(xs)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [270]:
np.log1p(xs)

array([0.        , 0.69314718, 1.60943791, 2.30258509, 2.83321334,
       3.25809654, 3.61091791, 3.91202301, 4.17438727, 4.40671925])

### Example 2

In [213]:
n = 10

xs = np.random.rand(n)
ys = np.random.rand(n)

s = 0
for i in range(n):
    s += xs[i] * ys[i]
s

2.0769221461759515

In [214]:
np.dot(xs, ys)

2.0769221461759515

In [215]:
xs @ ys

2.0769221461759515

### Example 3

\begin{align}
y_0 &= \alpha + \beta_1 x_1 + \beta_2 x_2 \\
y_1 &= \alpha + \beta_1 x_1 + \beta_2 x_2 \\
y_2 &= \alpha + \beta_1 x_1 + \beta_2 x_2 \\
\end{align}




In [248]:
m = 3
n = 2

alpha = np.random.rand(1)
betas = np.random.rand(n,1)
xs = np.random.rand(m,n)

In [249]:
alpha

array([0.62163796])

In [250]:
betas

array([[0.29867887],
       [0.83188591]])

In [251]:
xs

array([[0.87217023, 0.62017111],
       [0.56349838, 0.49957635],
       [0.60598475, 0.79513091]])

### Using loops

In [252]:
ys = np.zeros((m,1))
for i in range(m):
    ys[i] = alpha
    for j in range(n):
        ys[i] += betas[j] * xs[i,j]
ys

array([[1.39804838],
       [1.20553354],
       [1.464091  ]])

### Removing inner loop

In [253]:
ys = np.zeros((m,1))
for i in range(m):
    ys[i] = alpha + xs[i,:].T @ betas
ys

array([[1.39804838],
       [1.20553354],
       [1.464091  ]])

### Removing all loops

In [254]:
ys = alpha + xs @ betas
ys

array([[1.39804838],
       [1.20553354],
       [1.464091  ]])

### Alternative approach

The calculaiton with explicit intercepts and coefficients is common in deep learning, where $\alpha$ is called the bias ($b$) and $\beta$ are called the weights ($w$), and each equation is $y[i] = b + w[i]*x[i]$.

It is common in statisiics to use an augmented matrix in which the first column is all ones, so that all that is needed is a single matrix multiplicaiotn.

In [255]:
X = np.c_[np.ones(m), xs]
X

array([[1.        , 0.87217023, 0.62017111],
       [1.        , 0.56349838, 0.49957635],
       [1.        , 0.60598475, 0.79513091]])

In [259]:
alpha

array([0.62163796])

In [260]:
betas

array([[0.29867887],
       [0.83188591]])

In [263]:
betas_ = np.concatenate([[alpha], betas])
betas_

array([[0.62163796],
       [0.29867887],
       [0.83188591]])

In [265]:
ys = X @ betas_
ys

array([[1.39804838],
       [1.20553354],
       [1.464091  ]])