# Supplementary Practice Problems

These are similar to programming problems you may encounter in the mid-terms. They are not graded but we will review them in lab sessions.

For these questions, you should try to solve the problem manually first (or at least detail out the steps if the algebra is too horrible), then use `scipy.linalg` package routine(s) to solve.

**1**. Write down the full-matrix, block matrix and outer product forms of the SVD using $\LaTeX$ in a markdown cell.

$$
A = U \Sigma V^T
$$

$$
A = \begin{bmatrix}
U_1 & U_2
\end{bmatrix}\begin{bmatrix}
\Sigma_1 & 0 \\
0 & 0 
\end{bmatrix}\begin{bmatrix}
V_1^T \\
V_2^T
\end{bmatrix}
$$

$$
A = \sum_{i=1}^r \sigma u_i v_i^T
$$

**2**. Let
$$
u = \begin{bmatrix}
1 \\
2 \\
3 
\end{bmatrix}
$$
Find a non-zero vector $v$ that is orthogonal to $u$, and another non-zero vector $w$ that is orthogonal to both $u$ and $v$. Construct an orthogonal matrix $Q$ using the unit versions of $u, v, w$. What is the inverse of $Q$?

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
u = np.array([1,2,3]).reshape(-1,1)
v = np.array([1,1,-1]).reshape(-1,1)

For 2D and 3D vectors, you can use the cross product.

In [3]:
w1 = np.cross(u.squeeze(), v.squeeze()).reshape(-1,1)
w1

array([[-5],
       [ 4],
       [-1]])

Alternatively, use projection.

In [4]:
A = np.c_[u, v]
A

array([[ 1,  1],
       [ 2,  1],
       [ 3, -1]])

In [5]:
P = A @ la.inv(A.T @ A) @ A.T
w2 = np.array([1,1,1])
w2 = w2 - P@w2
w2

array([ 0.23809524, -0.19047619,  0.04761905])

In [6]:
u.T @ v, v.T @ w1, w1.T @ u

(array([[0]]), array([[0]]), array([[0]]))

In [7]:
u.T @ v, v.T @ w2, w2.T @ u

(array([[0]]), array([-1.11022302e-16]), array([5.55111512e-16]))

In [8]:
Q = la.orth(np.c_[u, v, w1])
Q

array([[ 0.77151675, -0.26726124, -0.57735027],
       [-0.6172134 , -0.53452248, -0.57735027],
       [ 0.15430335, -0.80178373,  0.57735027]])

In [9]:
Q.T

array([[ 0.77151675, -0.6172134 ,  0.15430335],
       [-0.26726124, -0.53452248, -0.80178373],
       [-0.57735027, -0.57735027,  0.57735027]])

In [10]:
np.round(Q @ Q.T, 10).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**3**. Find a basis for the 4 fundamental spaces of $A$, where
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7
\end{bmatrix}
$$
State the dimension of each basis, and the dimension of the space of the basis vectors.

In [11]:
A = np.array([
    [1,2,3,3],
    [2,0,6,2],
    [3,4,9,7]
])

In [12]:
U, s, Vt = la.svd(A)

In [13]:
tol = s.max() * max(A.shape) * np.finfo(float).eps

In [14]:
r = np.sum(s > tol)
r

2

$C(A)$

In [15]:
U[:, :r]

array([[-0.31994238, -0.36841839],
       [-0.41936816,  0.88119879],
       [-0.84956884, -0.29623738]])

$N(A^T)$

In [16]:
U[:, r:]

array([[-0.87287156],
       [-0.21821789],
       [ 0.43643578]])

Check

In [17]:
np.around(A.T @ U[:, r:], 10)

array([[0.],
       [0.],
       [0.],
       [0.]])

$C(A^T)$

In [18]:
Vt[:r, :].T

array([[-0.25358142,  0.17588223],
       [-0.27620609, -0.66896915],
       [-0.76074427,  0.52764668],
       [-0.52978752, -0.49308692]])

$N(A)$

In [19]:
Vt[r:, :].T

array([[-0.94190776,  0.1325582 ],
       [-0.14548851, -0.67455435],
       [ 0.26547308, -0.26903752],
       [ 0.14548851,  0.67455435]])

Check

In [20]:
np.around(A @ Vt[r:, :].T, 10)

array([[ 0., -0.],
       [-0., -0.],
       [-0., -0.]])

**4**. Find the projection of
$$
b = \begin{bmatrix}
3 \\
2 \\
1
\end{bmatrix}
$$
on the column space of $A$ by using the projection matrix, where 
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7
\end{bmatrix}
$$

In [21]:
CA = U[:, :r]
CA

array([[-0.31994238, -0.36841839],
       [-0.41936816,  0.88119879],
       [-0.84956884, -0.29623738]])

In [22]:
P = CA @ la.inv(CA.T @ CA) @ CA.T

In [23]:
b = np.array([3,2,1]).reshape(-1,1)

In [24]:
P @ b

array([[0.71428571],
       [1.42857143],
       [2.14285714]])

Check

In [25]:
P

array([[ 0.23809524, -0.19047619,  0.38095238],
       [-0.19047619,  0.95238095,  0.0952381 ],
       [ 0.38095238,  0.0952381 ,  0.80952381]])

In [26]:
A = np.array([
    [1,2,3,3],
    [2,0,6,2],
    [3,4,9,7]
])

In [27]:
x, res, rank, s = la.lstsq(A, b)

/usr/local/lib/python3.6/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


In [28]:
A @ x

array([[0.71428571],
       [1.42857143],
       [2.14285714]])

**5**. What is the inverse of
$$
A = \begin{bmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0
\end{bmatrix}
$$

In [29]:
A = np.eye(4)[:, [2,3,1,0]].astype('int')

In [30]:
A

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [31]:
A.T

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [32]:
A @ A.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**6**. Find the eigenvalues and eigenvectors of $A^TA$, and find an eigendecomposition of $A^TA = V \Lambda V^T$. Finally, construct the SVD of $A$ and use it to generate $A$
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 11 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix}
$$

In [33]:
A = np.array([
    [1,2,3,3],
    [2,0,6,11],
    [3,4,9,7],
    [4,4,4,4]
])

In [34]:
np.linalg.matrix_rank(A)

4

In [35]:
e, v = la.eigh(A.T @ A)

In [36]:
idx = np.argsort(e)[::-1]

In [37]:
D = np.diag(e[idx])
V = v[:, idx]

Check if V is orthogonal

In [38]:
np.around(V @ V.T, 10)

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1., -0.],
       [-0.,  0., -0.,  1.]])

In [39]:
A.T @ A

array([[ 30,  30,  58,  62],
       [ 30,  36,  58,  50],
       [ 58,  58, 142, 154],
       [ 62,  50, 154, 195]])

In [40]:
(V @ D @ V.T).astype('int')

array([[ 29,  30,  57,  61],
       [ 30,  35,  57,  49],
       [ 57,  57, 141, 153],
       [ 61,  49, 153, 194]])

In [41]:
S = D**0.5

In [42]:
U = A @ V @ np.diag(1/np.diag(S))

In [43]:
np.around(U.T @ U, 3)

array([[ 1.,  0., -0.,  0.],
       [ 0.,  1.,  0., -0.],
       [-0.,  0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

In [44]:
A

array([[ 1,  2,  3,  3],
       [ 2,  0,  6, 11],
       [ 3,  4,  9,  7],
       [ 4,  4,  4,  4]])

In [45]:
np.around(U @ S @ V.T, 0).astype('int')

array([[ 1,  2,  3,  3],
       [ 2,  0,  6, 11],
       [ 3,  4,  9,  7],
       [ 4,  4,  4,  4]])

**7**. Find an orthogonal basis and the QR decomposition for
$$
A = \begin{bmatrix}
1 & 2 & 0 \\
1 & 0 & 2 \\
0 & 1 & 2
\end{bmatrix}
$$

In [46]:
A = np.array([
    [1,2,0],
    [1,0,2],
    [0,1,2]
])

You should try out Gram-Schmidt. I am being lazy here.

In [47]:
Q, R = la.qr(A)

In [48]:
Q

array([[-0.70710678,  0.57735027, -0.40824829],
       [-0.70710678, -0.57735027,  0.40824829],
       [-0.        ,  0.57735027,  0.81649658]])

In [49]:
np.around(R, 3)

array([[-1.414, -1.414, -1.414],
       [ 0.   ,  1.732,  0.   ],
       [ 0.   ,  0.   ,  2.449]])

**8**. Solve the following problem
$$
\begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 11 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{bmatrix} = \begin{bmatrix}
4 \\
3 \\
2 \\
1
\end{bmatrix}
$$
using the following factorizations
- Gaussian elimination
- LU
- LDU
- QR
- SVD

In [50]:
A = np.array([
    [1,2,3,3],
    [2,0,6,11],
    [3,4,9,7],
    [4,4,4,4]
])

In [51]:
b = np.array([4,3,2,1]).reshape(-1,1)

Check

In [52]:
la.solve(A, b)

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

LU

In [53]:
P, L, U = la.lu(A)

In [54]:
A

array([[ 1,  2,  3,  3],
       [ 2,  0,  6, 11],
       [ 3,  4,  9,  7],
       [ 4,  4,  4,  4]])

In [55]:
P @ L @ U

array([[ 1.,  2.,  3.,  3.],
       [ 2.,  0.,  6., 11.],
       [ 3.,  4.,  9.,  7.],
       [ 4.,  4.,  4.,  4.]])

In [56]:
z = P.T @ b
y = la.solve_triangular(L, z, lower=True)
x = la.solve_triangular(U, y, lower=False)

In [57]:
x

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

LDU

In [58]:
P, L, U = la.lu(A)

In [59]:
U

array([[ 4.  ,  4.  ,  4.  ,  4.  ],
       [ 0.  , -2.  ,  4.  ,  9.  ],
       [ 0.  ,  0.  ,  8.  ,  8.5 ],
       [ 0.  ,  0.  ,  0.  ,  2.25]])

In [60]:
D = np.diag(np.diag(U))
D

array([[ 4.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  8.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  2.25]])

In [61]:
U = U/np.diag(U)[:, None]

In [62]:
z = P.T @ b
y = la.solve_triangular(L, z, lower=True)
x = la.solve_triangular(D @ U, y, lower=False)
x

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

QR

In [63]:
Q, R = la.qr(A)

In [64]:
y = Q.T @ b

In [65]:
la.solve_triangular(R, y, lower=False)

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

SVD

In [66]:
U, s, Vt = la.svd(A)

In [67]:
V = Vt.T

In [68]:
V @ np.diag(1/s) @ U.T @ b

array([[-3.29166667],
       [ 3.33333333],
       [-1.45833333],
       [ 1.66666667]])

**9**. Let $A$ be the plane spanned by the vectors

$$ v_1
\begin{bmatrix}
1 \\
0 \\
1 \\
0
\end{bmatrix}, v_2 = \begin{bmatrix}
1 \\
2 \\
3 \\
4
\end{bmatrix}
$$
What is the point on the plane nearest to the vectors $b_1$ and $b_2$.
$$
b_1 = \begin{bmatrix}
3 \\
2 \\
5 \\
4
\end{bmatrix}, b_2 = \begin{bmatrix}
3 \\
2 \\
0 \\
4
\end{bmatrix}
$$
Find the orthogonal distance from $b_1$ and $b_2$ to its nearest point.

In [69]:
v1 = np.array([1,0,1,0]).reshape(-1,1)
v2 = np.array([1,2,3,4]).reshape(-1,1)
b1 = np.array([3,2,5,4]).reshape(-1,1)
b2 = np.array([3,2,0,4]).reshape(-1,1)

In [70]:
A = np.c_[v1, v2]

**Using `lstsq`**

In [71]:
x, res, rank, s = la.lstsq(A, b1)

Point nearest b1

In [72]:
A @ x

array([[3.],
       [2.],
       [5.],
       [4.]])

Distance away from plane

In [73]:
np.sqrt(res)

array([4.4408921e-16])

In [74]:
x, res, rank, s = la.lstsq(A, b2)

Point nearest b2

In [75]:
x

array([[-0.04545455],
       [ 0.77272727]])

Distance away from plane

In [76]:
np.sqrt(res)

array([3.37099931])

**Using projections**

We would normally use `lstsq`. This is just to illustrate the geometric concepts involved.

In [77]:
P = A @ la.inv(A.T @ A) @ A.T

In [78]:
Q = np.eye(P.shape[0]) - P

Point nearest b1

In [79]:
P @ b1

array([[3.],
       [2.],
       [5.],
       [4.]])

Distance away from plane

In [80]:
la.norm(Q @ b1)

1.26219223971514e-15

Point nearest b2

In [81]:
P @ b2

array([[0.72727273],
       [1.54545455],
       [2.27272727],
       [3.09090909]])

Distance away from plane

In [82]:
la.norm(Q @ b2)

3.3709993123162105

**10**. Let
$$
A = \begin{bmatrix}
1 & 2 & 3 & 3 \\
2 & 0 & 6 & 2 \\
3 & 4 & 9 & 7 \\
4 & 4 & 4 & 4
\end{bmatrix}
$$
- What is the rank of $A$
- What is the condition number of $A$?
- What is the best rank-1 and rank-2 approximation of $A$?
- What is the distance between $A$ and the best rank-1 and rank-2 approximation of $A$ using the Frobenius norm?

In [83]:
A = np.array([
    [1,2,3,3],
    [2,0,6,2],
    [3,4,9,7],
    [4,4,4,4]
])

In [84]:
np.linalg.matrix_rank(A)

3

In [85]:
tol = s.max() * max(A.shape) * np.finfo(float).eps

In [86]:
U, s, Vt = la.svd(A)

In [87]:
V = Vt.T

In [88]:
rank = np.sum(s > tol)
rank

3

In [89]:
s[0]/s[-1]

9.164863848728758e+16

Best rank-1 approximation

In [90]:
r1 = s[:1] * U[:, :1] @ V[:, :1].T
r1

array([[1.47375548, 1.56459164, 3.36168067, 2.50855423],
       [1.86658588, 1.98163448, 4.25773866, 3.17721087],
       [3.8808039 , 4.12000052, 8.85223067, 6.6057139 ],
       [2.36414554, 2.50986165, 5.39268725, 4.0241325 ]])

Best rank-2 approximation

In [91]:
s[:2]

array([16.40254443,  3.62778422])

In [92]:
r2 = s[:2] * U[:, :2] @ V[:, :2].T
r2

array([[1.61192417, 1.92808576, 3.0343619 , 2.63930463],
       [1.15125625, 0.09974563, 5.95233977, 2.50028739],
       [3.79947646, 3.90604433, 9.04489368, 6.52875295],
       [2.97629616, 4.1203072 , 3.94251509, 4.60341666]])

Distance to rank-1

In [93]:
la.norm(A - r1)

4.117831498626227

Distance to rank-2

In [94]:
la.norm(A - r2)

1.9482602247661711